/*
  This file is automatically generated. Any changes will be overwritten.
  Modify edit-inventory-transaction.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { LabelComponent } from '@radzen/angular/dist/label';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { DropDownDataGridComponent } from '@radzen/angular/dist/dropdown-datagrid';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { NumericComponent } from '@radzen/angular/dist/numeric';
import { DatePickerComponent } from '@radzen/angular/dist/datepicker';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';

import { ConfigService } from '../config.service';

import { ConDataService } from '../con-data.service';
import { SecurityService } from '../security.service';

export class EditInventoryTransactionGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('closeLabel') closeLabel: LabelComponent;
  @ViewChild('closeButton') closeButton: ButtonComponent;
  @ViewChild('label0') label0: LabelComponent;
  @ViewChild('button0') button0: ButtonComponent;
  @ViewChild('form0') form0: TemplateFormComponent;
  @ViewChild('productIdLabel') productIdLabel: LabelComponent;
  @ViewChild('productId') productId: DropDownDataGridComponent;
  @ViewChild('productIdRequiredValidator') productIdRequiredValidator: RequiredValidatorComponent;
  @ViewChild('quantityLabel') quantityLabel: LabelComponent;
  @ViewChild('quantity') quantity: NumericComponent;
  @ViewChild('quantityRequiredValidator') quantityRequiredValidator: RequiredValidatorComponent;
  @ViewChild('transactionDateLabel') transactionDateLabel: LabelComponent;
  @ViewChild('transactionDate') transactionDate: DatePickerComponent;
  @ViewChild('transactionTypeLabel') transactionTypeLabel: LabelComponent;
  @ViewChild('transactionType') transactionType: TextBoxComponent;
  @ViewChild('transactionTypeRequiredValidator') transactionTypeRequiredValidator: RequiredValidatorComponent;
  @ViewChild('button3') button3: ButtonComponent;
  @ViewChild('button4') button4: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  conData: ConDataService;

  security: SecurityService;
  hasChanges: any;
  canEdit: any;
  inventorytransaction: any;
  getByProductsForProductIDResult: any;
  getProductsForProductIDPageSize: any;
  getProductsForProductIDResult: any;
  getProductsForProductIDCount: any;
  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.conData = this.injector.get(ConDataService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.hasChanges = false;

    this.canEdit = true;

    this.conData.getInventoryTransactionByTransactionId(null, this.parameters.TransactionID)
    .subscribe((result: any) => {
      this.inventorytransaction = result;

      if (this.inventorytransaction.ProductID != null) {
              this.conData.getProductByProductId(null, this.inventorytransaction.ProductID)
        .subscribe((result: any) => {
              this.getByProductsForProductIDResult = result;
        }, (result: any) => {
      
        });
      }
    }, (result: any) => {
      this.canEdit = !(result.status == 400);
    });

    this.getProductsForProductIDPageSize = 10;

    this.conData.getProducts(null, this.getProductsForProductIDPageSize, 0, null, true, null, null, null)
    .subscribe((result: any) => {
      this.getProductsForProductIDResult = result.value;

      this.getProductsForProductIDCount = result['@odata.count'];
    }, (result: any) => {

    });
  }

  closeButtonClick(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }

  button0Click(event: any) {
    this.load()
  }

  form0Submit(event: any) {
    this.conData.updateInventoryTransaction(`Product`, this.parameters.TransactionID, event)
    .subscribe((result: any) => {
      if (this.dialogRef) {
        this.dialogRef.close();
      } else {
        this._location.back();
      }
    }, (result: any) => {
      this.hasChanges = result.status == 412;

      this.canEdit = !(result.status == 400);

      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to update InventoryTransaction` });
    });
  }

  ProductIDLoadData(event: any) {
    this.conData.getProducts(`${event.filter}`, event.top, event.skip, `${event.orderby}`, true, null, null, null)
    .subscribe((result: any) => {
      this.getProductsForProductIDResult = result.value;

      this.getProductsForProductIDCount = result['@odata.count'];
    }, (result: any) => {

    });
  }

  button4Click(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }
}
